---
services:
  whoami:
    image: traefik/whoami:v1.11.0
    container_name: secure-whoami
    read_only: true
    tmpfs:
      - /tmp
    #  tmp --is incorrect use tmps - /tmp  — the path must be absolute.
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:80"
    #  health check for the service
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: "no"
